//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.PictureProject = new HashSet<PictureProject>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public byte[] MainPicture { get; set; }
        public string text { get; set; }
        public Nullable<int> ManWithResumeId { get; set; }
        public string description { get; set; }
    
        public virtual ManWithResume ManWithResume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PictureProject> PictureProject { get; set; }
    }
}
