//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForCompanyMeetingProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.ManWithResume = new HashSet<ManWithResume>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string LegalForm { get; set; }
        public string number { get; set; }
        public string email { get; set; }
        public string telegram { get; set; }
        public string adout { get; set; }
        public byte[] BackgroundImage { get; set; }
        public byte[] ProfilePhoto { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ManWithResume> ManWithResume { get; set; }
    }
}
